'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';

type RecordItem={id:string;project_name:string;keyword:string;drug_name:string;manager:string;boss_group:string;start_date:string;end_date:string;contract_amount:number;image_url:string;landing_url:string;status:string;created_at:string};
type Metric={keyword:string;boss_group:string;pv:number;gmv:number;price:number;historical_average:number;grade:string};
type Log={id:number;submission_id:string;action:string;actor:string;ip:string;created_at:string};
type View='dashboard'|'new'|'pricing'|'ops'|'logs';

const today='2026-08-31';
const emptyForm={projectName:'',keyword:'',drugName:'',manager:'',bossGroup:'',startDate:'2026-09-01',endDate:'2026-09-30',contractAmount:'',imageUrl:'',landingUrl:''};
const icons:Record<View,string>={dashboard:'▦',new:'＋',pricing:'◇',ops:'✓',logs:'↻'};
const labels:Record<View,string>={dashboard:'资源位看板',new:'新建提报',pricing:'询价与价值',ops:'收口工作台',logs:'操作记录'};
const fmt=(n:number)=>new Intl.NumberFormat('zh-CN').format(n);
const compact=(n:number)=>n>=10000?`${(n/10000).toFixed(n>=1000000?0:1)}万`:String(n);
const daysLeft=(end:string)=>Math.ceil((new Date(`${end}T00:00:00`).getTime()-new Date(`${today}T00:00:00`).getTime())/86400000);
const statusOf=(r:RecordItem)=>r.status==='待配置'?'待配置':r.end_date<today?'已结束':r.start_date>today?'未开始':daysLeft(r.end_date)<=7?'即将到期':r.status;

export default function Home(){
  const [view,setView]=useState<View>('dashboard'); const [records,setRecords]=useState<RecordItem[]>([]); const [metrics,setMetrics]=useState<Metric[]>([]); const [logs,setLogs]=useState<Log[]>([]); const [loading,setLoading]=useState(true);
  const [query,setQuery]=useState(''); const [filter,setFilter]=useState('全部状态'); const [mode,setMode]=useState<'table'|'gantt'>('table'); const [selected,setSelected]=useState<RecordItem|null>(null); const [toast,setToast]=useState('');
  const load=async()=>{setLoading(true);try{const res=await fetch('/api/submissions');const data=await res.json();setRecords(data.records??[]);setMetrics(data.metrics??[]);setLogs(data.logs??[])}finally{setLoading(false)}};
  useEffect(()=>{load()},[]); useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),3200);return()=>clearTimeout(t)}},[toast]);
  const navigate=(next:View)=>{setView(next);setSelected(null);window.scrollTo({top:0,behavior:'smooth'})};
  const active=records.filter((r)=>r.start_date<=today&&r.end_date>=today); const expiring=records.filter((r)=>daysLeft(r.end_date)>=0&&daysLeft(r.end_date)<=7); const pending=records.filter((r)=>r.status==='待配置');
  return <main className="app-shell">
    <aside className="sidebar">
      <button className="brand" onClick={()=>navigate('dashboard')}><span className="brand-mark">药</span><span>药师金刚</span></button>
      <nav>{(['dashboard','new','pricing','ops','logs'] as View[]).map((item)=><button key={item} className={`nav-item ${view===item?'active':''}`} onClick={()=>navigate(item)}><i>{icons[item]}</i><span>{labels[item]}</span>{item==='ops'&&<b>{pending.length}</b>}</button>)}</nav>
      <div className="side-note"><strong>内部数据 · 请勿外传</strong><span>当前为脱敏浏览模式</span></div>
    </aside>
    <section className="main-area">
      <Header view={view} navigate={navigate}/>
      <div className="content">
        {loading?<Loading/>:view==='dashboard'?<Dashboard records={records} active={active.length} expiring={expiring.length} pending={pending.length} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} mode={mode} setMode={setMode} selected={setSelected} navigate={navigate}/>:view==='new'?<NewReport records={records} onSuccess={()=>{setToast('提报成功，已进入收口人待配置队列');load();navigate('dashboard')}}/>:view==='pricing'?<Pricing metrics={metrics}/>:view==='ops'?<Ops records={records} onUpdate={async(id,status)=>{await fetch('/api/submissions',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,status})});setToast(`状态已更新为「${status}」`);load()}}/>:<Logs logs={logs} records={records}/>} 
      </div>
    </section>
    {selected&&<Detail record={selected} logs={logs.filter((l)=>l.submission_id===selected.id)} close={()=>setSelected(null)}/>} {toast&&<div className="toast">✓ {toast}</div>}
  </main>
}

function Header({view,navigate}:{view:View;navigate:(v:View)=>void}){const titles={dashboard:['资源位全景看板','实时掌握排期占用与项目进展'],new:['新建资源位提报','填写信息后自动校验关键词档期'],pricing:['询价与价值看板','用历史数据支持资源位定价与售卖'],ops:['收口人配置工作台','集中处理待配置与即将上线项目'],logs:['操作记录','追踪系统内全部关键操作']};return <header className="topbar"><div><h1>{titles[view][0]}</h1><p>{titles[view][1]}</p></div><div className="top-actions">{view!=='pricing'&&<button className="ghost-btn" onClick={()=>navigate('pricing')}>询价看板 ↗</button>}{view!=='new'&&<button className="primary-btn" onClick={()=>navigate('new')}>＋ 新建提报</button>}</div></header>}
function Loading(){return <div className="loading"><span/><p>正在同步资源位数据…</p></div>}

function Dashboard({records,active,expiring,pending,query,setQuery,filter,setFilter,mode,setMode,selected,navigate}:{records:RecordItem[];active:number;expiring:number;pending:number;query:string;setQuery:(v:string)=>void;filter:string;setFilter:(v:string)=>void;mode:'table'|'gantt';setMode:(v:'table'|'gantt')=>void;selected:(r:RecordItem)=>void;navigate:(v:View)=>void}){
  const visible=records.filter((r)=>{const hit=[r.keyword,r.project_name,r.drug_name,r.manager].some((v)=>v.includes(query));return hit&&(filter==='全部状态'||statusOf(r)===filter)});
  return <>
    <section className="hero-strip"><div><span className="eyebrow">TODAY · 资源位健康度</span><h2>排期整体稳定，<em>{pending} 项待配置</em></h2><p>{Math.min(pending,3)} 个项目将在近期上线，请收口人及时完成配置。</p></div><button onClick={()=>navigate('ops')}>查看待办 <span>→</span></button></section>
    <section className="metric-grid">{[{label:'当前在线',value:active,note:'资源位运行中',tone:'green'},{label:'未来 7 天到期',value:expiring,note:'需跟进续期',tone:'orange'},{label:'待配置提报',value:pending,note:'收口人待处理',tone:'red'},{label:'可售关键词',value:126-records.length,note:'未来 30 天估算',tone:'blue'}].map((x)=><article className="metric-card" key={x.label}><div><span>{x.label}</span><i className={`dot ${x.tone}`}/></div><strong>{x.value}</strong><small>{x.note}</small></article>)}</section>
    <section className="panel"><div className="panel-head"><div><h3>资源位排期</h3><p>共 {records.length} 条提报记录 · 数据实时同步</p></div><div className="segmented"><button className={mode==='table'?'selected':''} onClick={()=>setMode('table')}>表格视图</button><button className={mode==='gantt'?'selected':''} onClick={()=>setMode('gantt')}>甘特视图</button></div></div>
      <div className="toolbar"><label className="search">⌕<input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="搜索关键词、药品、项目或 PM"/></label><select value={filter} onChange={(e)=>setFilter(e.target.value)}><option>全部状态</option><option>运行中</option><option>待配置</option><option>即将到期</option><option>已结束</option><option>未开始</option></select><button>2026 年 9 月⌄</button><span className="result-count">{visible.length} 条结果</span></div>
      {mode==='table'?<ResourceTable records={visible} selected={selected}/>:<Gantt records={visible}/>} </section>
  </>
}
function ResourceTable({records,selected}:{records:RecordItem[];selected:(r:RecordItem)=>void}){return <div className="table-wrap"><table><thead><tr><th>金刚关键词</th><th>项目名称</th><th>药品通用名</th><th>项目经理</th><th>上线周期</th><th>当前状态</th><th>剩余时间</th><th/></tr></thead><tbody>{records.map((r)=>{const s=statusOf(r),left=daysLeft(r.end_date);return <tr key={r.id} onClick={()=>selected(r)}><td><strong>{r.keyword}</strong><small>{r.boss_group}</small></td><td>{r.project_name}</td><td>{r.drug_name}</td><td><span className="avatar">{r.manager[0]}</span>{r.manager}</td><td>{r.start_date.slice(5).replace('-','.')} — {r.end_date.slice(5).replace('-','.')}</td><td><span className={`status status-${s}`}>{s}</span></td><td className={left<=7&&left>=0?'urgent':''}>{left<0?'已结束':left===0?'今日到期':`${left} 天`}</td><td>›</td></tr>})}</tbody></table>{!records.length&&<Empty text="没有找到匹配的资源位"/>}</div>}
function Gantt({records}:{records:RecordItem[]}){const days=Array.from({length:30},(_,i)=>i+1);return <div className="gantt"><div className="gantt-head"><b>关键词 / 项目</b>{[1,5,10,15,20,25,30].map((d)=><span key={d}>{d}日</span>)}</div>{records.map((r)=>{const start=Math.max(1,Number(r.start_date.slice(8))),end=r.end_date.slice(0,7)==='2026-09'?Number(r.end_date.slice(8)):30;return <div className="gantt-row" key={r.id}><div><strong>{r.keyword}</strong><small>{r.project_name}</small></div><div className="track">{days.map((d)=><i key={d}/>) }<span className={`bar bar-${statusOf(r)}`} style={{left:`${((start-1)/30)*100}%`,width:`${Math.max(4,((end-start+1)/30)*100)}%`}}>{start<=end&&`${start}—${end}日`}</span></div></div>})}<div className="gantt-legend"><span><i className="legend-live"/>已占用</span><span><i className="legend-pending"/>待配置</span><span><i className="legend-free"/>空闲可售</span></div></div>}

function NewReport({records,onSuccess}:{records:RecordItem[];onSuccess:()=>void}){const [form,setForm]=useState(emptyForm);const [submitting,setSubmitting]=useState(false);const [step,setStep]=useState(1);const set=(k:string,v:string)=>setForm((f)=>({...f,[k]:v}));useEffect(()=>{const draft=localStorage.getItem('kingkong-draft');if(draft)try{setForm(JSON.parse(draft))}catch{}},[]);
  const conflict=useMemo(()=>records.find((r)=>r.keyword.trim()===form.keyword.trim()&&r.start_date<=form.endDate&&r.end_date>=form.startDate),[records,form.keyword,form.startDate,form.endDate]);
  const nextDate=conflict?new Date(new Date(`${conflict.end_date}T00:00:00`).getTime()+86400000).toISOString().slice(0,10):'';
  const submit=async(e:FormEvent)=>{e.preventDefault();if(conflict)return;setSubmitting(true);const res=await fetch('/api/submissions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...form,contractAmount:Number(form.contractAmount)})});const data=await res.json();setSubmitting(false);if(res.ok){localStorage.removeItem('kingkong-draft');onSuccess()}else alert(data.error??'提交失败')};
  const saveDraft=()=>{localStorage.setItem('kingkong-draft',JSON.stringify(form));alert('草稿已保存在当前设备')};
  return <div className="form-layout"><section className="form-main"><div className="steps"><span className={step>=1?'on':''}><b>1</b>项目信息</span><i/><span className={step>=2?'on':''}><b>2</b>资源配置</span><i/><span className={step>=3?'on':''}><b>3</b>确认提报</span></div><form onSubmit={submit}>
    <div className="form-section"><div className="section-title"><b>01</b><div><h3>基础项目信息</h3><p>用于归档合同与明确项目责任人</p></div></div><div className="form-grid"><Field label="项目名称 *"><input required value={form.projectName} onFocus={()=>setStep(1)} onChange={(e)=>set('projectName',e.target.value)} placeholder="如：秋季呼吸健康联合营销"/></Field><Field label="项目经理姓名 *"><input required value={form.manager} onChange={(e)=>set('manager',e.target.value)} placeholder="请输入负责人姓名"/></Field><Field label="药品通用名 *"><input required value={form.drugName} onChange={(e)=>set('drugName',e.target.value)} placeholder="如：氯雷他定片"/></Field><Field label="BOSS 组归属 *"><select required value={form.bossGroup} onChange={(e)=>set('bossGroup',e.target.value)}><option value="">请选择业务组</option><option>慢病一组</option><option>OTC一组</option><option>OTC二组</option><option>滋补营养组</option><option>消化二组</option></select></Field><Field label="合同金额（元）*" wide><input required type="number" value={form.contractAmount} onChange={(e)=>set('contractAmount',e.target.value)} placeholder="请输入合同含税金额"/></Field></div></div>
    <div className="form-section"><div className="section-title"><b>02</b><div><h3>资源位配置</h3><p>系统将在输入关键词与周期后自动校验冲突</p></div></div><div className="form-grid"><Field label="金刚关键词 *" wide><div className={`keyword-input ${conflict?'has-error':form.keyword&&form.startDate&&form.endDate?'has-success':''}`}><input required value={form.keyword} onFocus={()=>setStep(2)} onChange={(e)=>set('keyword',e.target.value)} placeholder="请输入需要占用的搜索关键词"/><span>{conflict?'!':form.keyword?'✓':'⌕'}</span></div>{conflict?<div className="conflict"><strong>档期冲突，暂不可提报</strong><p>该词正被「{conflict.project_name}」占用，负责人 {conflict.manager}，将于 {conflict.end_date} 释放。</p><button type="button" onClick={()=>{set('startDate',nextDate);const end=new Date(`${nextDate}T00:00:00`);end.setDate(end.getDate()+29);set('endDate',end.toISOString().slice(0,10))}}>采用推荐档期：{nextDate} 起 →</button></div>:form.keyword&&form.startDate&&form.endDate?<div className="available">✓ 当前关键词在所选周期内可用</div>:null}</Field><Field label="上线开始日期 *"><input required type="date" value={form.startDate} onChange={(e)=>set('startDate',e.target.value)}/></Field><Field label="上线结束日期 *"><input required type="date" value={form.endDate} onChange={(e)=>set('endDate',e.target.value)}/></Field><Field label="金刚头图链接 *" wide><input required type="url" value={form.imageUrl} onChange={(e)=>set('imageUrl',e.target.value)} placeholder="https://...（建议 750 × 320）"/></Field><Field label="跳转落地页链接 *" wide><input required type="url" value={form.landingUrl} onChange={(e)=>set('landingUrl',e.target.value)} placeholder="https://item.jd.com/..."/></Field></div></div>
    <div className="form-actions"><button type="button" onClick={saveDraft}>存为草稿</button><button className="submit" disabled={!!conflict||submitting} onFocus={()=>setStep(3)}>{submitting?'正在校验并提报…':conflict?'存在档期冲突，无法提报':'确认并提交提报 →'}</button></div></form></section><aside className="form-aside"><h3>提报摘要</h3><dl><div><dt>关键词</dt><dd>{form.keyword||'待填写'}</dd></div><div><dt>上线周期</dt><dd>{form.startDate}<br/>至 {form.endDate}</dd></div><div><dt>负责人</dt><dd>{form.manager||'待填写'}</dd></div><div><dt>初始状态</dt><dd><span className="status status-待配置">待配置</span></dd></div></dl><div className="rule-note"><strong>冲突检测规则</strong><p>同一关键词的日期区间不可重叠。系统会在提交瞬间再次校验，避免多人同时提报造成撞单。</p></div><p className="privacy">合同金额等敏感数据在公共视图中默认脱敏。</p></aside></div>}
function Field({label,wide,children}:{label:string;wide?:boolean;children:React.ReactNode}){return <label className={`field ${wide?'wide':''}`}><span>{label}</span>{children}</label>}

function Pricing({metrics}:{metrics:Metric[]}){const [revealed,setRevealed]=useState(false);const [code,setCode]=useState('');const [showUnlock,setShowUnlock]=useState(false);const unlock=()=>{if(code==='JK2026'){setRevealed(true);setShowUnlock(false)}else alert('共享口令不正确')};return <><section className="pricing-hero"><div><span className="eyebrow">COMMERCIAL VALUE</span><h2>让每一个关键词，都有据可卖</h2><p>基于历史流量与成交数据，为资源位定价和客户沟通提供依据。</p></div><div className="pricing-stat"><span>关键词月均带动 GMV</span><strong>{revealed?'¥ 268.4 万':'¥ ***.* 万'}</strong><small>环比上月 +12.8%</small></div></section><section className="panel pricing-panel"><div className="panel-head"><div><h3>资源位询价表</h3><p>统计周期：2026 年 8 月 · 数据每周一更新</p></div><div className="price-actions"><button onClick={()=>setShowUnlock(true)}>{revealed?'◉ 已显示明文':'◉ 查看明文'}</button><button onClick={()=>window.print()}>⇩ 导出报价单</button></div></div><div className="table-wrap"><table><thead><tr><th>关键词 / 价值等级</th><th>BOSS 组归属</th><th>月曝光 PV</th><th>带动 GMV</th><th>历史成交均价</th><th>金刚刊例价</th><th>趋势</th></tr></thead><tbody>{metrics.map((m)=><tr key={m.keyword}><td><strong>{m.keyword}</strong><span className={`grade grade-${m.grade}`}>{m.grade}级</span></td><td>{m.boss_group}</td><td>{compact(m.pv)}</td><td>{revealed?`¥${compact(m.gmv)}`:`¥ ${compact(Math.floor(m.gmv/100000)*10)}万+`}</td><td>{revealed?`¥ ${fmt(m.historical_average)}`:'¥ ***，***'}</td><td><strong>{revealed?`¥ ${fmt(m.price)}`:'¥ ***，***'}</strong></td><td><span className="trend">↗ {m.grade==='S'?'18.6':'8.4'}%</span></td></tr>)}</tbody></table></div><div className="pricing-foot"><span>分级说明</span><i className="grade grade-S">S</i>高爆品 <i className="grade grade-A">A</i>高潜品 <i className="grade grade-B">B</i>常规品 <p>以上价格仅供内部业务报价参考</p></div></section>{showUnlock&&<div className="modal-backdrop"><div className="unlock-modal"><button className="close" onClick={()=>setShowUnlock(false)}>×</button><div className="lock-icon">⌁</div><h3>查看敏感数据</h3><p>请输入部门共享口令，明文仅在本次访问期间显示。</p><input autoFocus type="password" value={code} onChange={(e)=>setCode(e.target.value)} onKeyDown={(e)=>e.key==='Enter'&&unlock()} placeholder="请输入共享口令"/><button className="primary-btn" onClick={unlock}>确认查看</button><small>原型体验口令：JK2026</small></div></div>}</>}

function Ops({records,onUpdate}:{records:RecordItem[];onUpdate:(id:string,status:string)=>void}){const tasks=records.filter((r)=>['待配置','已上线'].includes(r.status)||statusOf(r)==='即将到期');return <><section className="ops-summary"><article><span>待配置</span><strong>{records.filter((r)=>r.status==='待配置').length}</strong><small>其中 2 项将在 3 天内上线</small></article><article><span>待确认上线</span><strong>{records.filter((r)=>r.status==='已上线').length}</strong><small>已完成后台配置</small></article><article><span>链接巡检异常</span><strong>0</strong><small className="ok">全部链接状态正常</small></article></section><section className="panel"><div className="panel-head"><div><h3>配置任务队列</h3><p>按上线时间自动排序，优先处理临近项目</p></div><button className="outline-btn">批量操作</button></div><div className="task-list">{tasks.map((r)=><article key={r.id}><div className="task-date"><b>{r.start_date.slice(8)}</b><span>{r.start_date.slice(5,7)}月</span></div><div className="task-main"><div><span className={`status status-${statusOf(r)}`}>{statusOf(r)}</span><small>{r.boss_group}</small></div><h3>{r.keyword} · {r.project_name}</h3><p>{r.drug_name}　|　负责人：{r.manager}　|　{r.start_date} 至 {r.end_date}</p></div><div className="task-actions">{r.status==='待配置'?<button className="primary-btn" onClick={()=>onUpdate(r.id,'已上线')}>确认配置完成</button>:r.status==='已上线'?<button className="primary-btn" onClick={()=>onUpdate(r.id,'运行中')}>确认开始运行</button>:<button onClick={()=>onUpdate(r.id,'已下线')}>确认下线</button>}<button>查看详情</button></div></article>)}{!tasks.length&&<Empty text="当前没有待处理任务"/>}</div></section></>}
function Logs({logs,records}:{logs:Log[];records:RecordItem[]}){return <section className="panel logs-panel"><div className="panel-head"><div><h3>审计日志</h3><p>所有新增与状态变更都会被记录</p></div><button className="outline-btn">导出日志</button></div><div className="timeline">{logs.length?logs.map((l)=><article key={l.id}><i/><div><strong>{l.action}</strong><p>{records.find((r)=>r.id===l.submission_id)?.project_name??'资源位记录'} · 操作人 {l.actor}</p></div><aside><span>{new Date(l.created_at).toLocaleString('zh-CN',{hour12:false})}</span><small>来源：{l.ip}</small></aside></article>):<Empty text="暂无操作记录，新的提报会显示在这里"/>}</div></section>}
function Detail({record,logs,close}:{record:RecordItem;logs:Log[];close:()=>void}){const steps=['草稿','待配置','已上线','运行中','已下线'];const current=Math.max(1,steps.indexOf(record.status));return <div className="drawer-backdrop" onMouseDown={close}><aside className="detail-drawer" onMouseDown={(e)=>e.stopPropagation()}><button className="close" onClick={close}>×</button><span className={`status status-${statusOf(record)}`}>{statusOf(record)}</span><h2>{record.project_name}</h2><p className="detail-keyword">金刚关键词 · <strong>{record.keyword}</strong></p><div className="lifecycle">{steps.map((s,i)=><span key={s} className={i<=current?'done':''}><i>{i<current?'✓':i+1}</i><small>{s}</small></span>)}</div><section><h3>项目档案</h3><dl className="detail-grid"><div><dt>药品通用名</dt><dd>{record.drug_name}</dd></div><div><dt>项目经理</dt><dd>{record.manager}</dd></div><div><dt>BOSS 组</dt><dd>{record.boss_group}</dd></div><div><dt>合同金额</dt><dd>¥ ***，***</dd></div><div><dt>上线周期</dt><dd>{record.start_date} 至 {record.end_date}</dd></div><div><dt>剩余时间</dt><dd>{Math.max(0,daysLeft(record.end_date))} 天</dd></div></dl><a href={record.landing_url} target="_blank">↗ 查看跳转落地页</a></section><section><h3>操作记录</h3>{logs.length?logs.map((l)=><p className="detail-log" key={l.id}><i/> <strong>{l.action}</strong><span>{new Date(l.created_at).toLocaleString('zh-CN')}</span></p>):<p className="muted">暂无变更记录</p>}</section><div className="drawer-actions"><button>发起变更申请</button><button className="primary-btn">复制项目链接</button></div></aside></div>}
function Empty({text}:{text:string}){return <div className="empty"><b>⌕</b><p>{text}</p></div>}
